### ISSUE TITLE
Add analytics to wiki

### ISSUE THREAD

**Issue by zisi** [satnogs/satnogs-org#163]

**Comment by axilleas** [comment]
* https://www.mediawiki.org/wiki/Extension:Piwik_Integration
* https://www.mediawiki.org/wiki/Extension:Google_Analytics_Integration

Αν θέτε βοήθεια να εγκατασταθούν σφυρίξτε. Ακόμα ο mediwiki ρόλος στο Ansible δεν έχει ολοκληρωθεί και βάζω τα extensia χειροκίνητα προς το παρόν.
