### ISSUE TITLE
Buy magnets for encoders

### ISSUE THREAD

**Issue by zisi** [satnogs/satnogs-org#183]
Diametric Magnet NdFeB, Grade N35, D6x2.5mm
http://ams.com/eng/Products/Position-Sensors/Magnets/AS5000-MD6H-3

**Comment by ppapadeas** [comment]
Ordered 3 samples.

**Comment by ppapadeas** [comment]
Samples arrived

**Comment by ppapadeas** [comment]
Need to buy 60. Pierros to proceed with order.

**Comment by ppapadeas** [comment]
Check with Petros on local vendor.

**Comment by zisi** [comment]
We buy [this magnet](https://www.magnet-shop.com/neodymium/discmagnets/discmagnet-4.0-x-4.0-mm-n35h-nickel-diametral-120c) for testing.

**Comment by ppapadeas** [comment]
Need to do a shopping stroll

**Comment by zisi** [comment]
We can buy [these magnets](https://www.aliexpress.com/item/100-pcs-NdFeB-Magnet-Disc-Dia-6x2-5-mm-0-236-Diametrically-Magnetized-Strong-Magnet-Neodymium/32639986878.html?ws_ab_test=searchweb0_0,searchweb201602_2_10091_10090_10088_10089,searchweb201603_1&btsid=30e9cd2c-1650-412b-940c-815c7d456839) for 30 stations.

**Comment by ppapadeas** [comment]
Purchase made!
