### ISSUE TITLE
30 Kits Buy List

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-org#192]

**Comment by zisi** [comment]
- [ ] T-slots
- [ ] Aluminum Axis Φ40mm
- [ ] Pulleys, Belts, Aluminum Box
- [ ] Wires, crimps, terminals female
- [ ] PCB and parts
- [ ] pro micro (arduino), PSU (voltage regulator)
- [ ] Magnets for encoders
- [ ] Rotator Cover (plexiglass)

**Comment by ppapadeas** [comment]
Need to break down to individual issues and close.

**Comment by zisi** [comment]
The individual issues are [#203](https://github.com/satnogs/satnogs-org/issues/203),
[#204](https://github.com/satnogs/satnogs-org/issues/204),
[#201](https://github.com/satnogs/satnogs-org/issues/201),
[#202](https://github.com/satnogs/satnogs-org/issues/202),
[#183](https://github.com/satnogs/satnogs-org/issues/183),
[#198](https://github.com/satnogs/satnogs-org/issues/198).

**Comment by ppapadeas** [comment]
Closed in favor the issues above.
