### ISSUE TITLE
Test diplexer with vna

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-org#31]

**Comment by zisi** [comment]
Transmission loss of Diplexer in VHF:
![vhf_diplexer](https://cloud.githubusercontent.com/assets/3720573/5726369/623642cc-9b63-11e4-9eb1-0076b14d7724.jpg)
3dB frequency is ~308MHz (is shifted)
Larger ripple compared with theoretical results
In 140 -150 MHz is ~ -3dB
In 435 - 438MHz droped to ~ -59dB

Transmission loss of Diplexer in UHF:
![uhf_diplexer](https://cloud.githubusercontent.com/assets/3720573/5726368/6221cec8-9b63-11e4-8d01-7b0251bf7e0f.jpg)
3dB frequency is ~316.48MHz (is shifted)
In 438MHz droped to -36.72dB
In 140 - 150 MHz droped to -57dB

**Comment by ppapadeas** [comment]
Diplexer v1 is not functioning according to specs.
