### ISSUE TITLE
[Infra] Cordinate communication with EDET

### ISSUE THREAD

**Issue by comzeradd** [satnogs/satnogs-org#42]

**Comment by ppapadeas** [comment]
Please respond for meeting this week. (asap)

**Comment by ppapadeas** [comment]
Elkos with Nemo to reach out

**Comment by ppapadeas** [comment]
Call offices

**Comment by johngian** [comment]
VM specs:

* VM1 (satnogs network/db)
 * 4 vCPUs, 4G RAM, 200G
* VM2 (other services)
 * 4 vCPUs, 4G RAM, 20G

**Comment by ppapadeas** [comment]
Received.
