### ISSUE TITLE
POE research

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-org#45]

**Comment by zisi** [comment]
Some notes for PoE
* power consumption of rotator (DC motors), 24V@0.6A
* power consumption of rotator (Stepper motors), 20V@0.5A [1](https://www.ethercalc.org/SatnogsPower)
* Switching regulator in rotator Vin:4-35V, Vout:1.5-35V, Imax:3A
* IEEE 802.3at-2009/PoE+ up to 25.5W [2](https://en.wikipedia.org/wiki/Power_over_Ethernet)
* Cat5 cable (24AWG) Imax ~0.5A, for two pairs (2x0.5)A [3](http://www.powerstream.com/Wire_Size.htm)
* Cat6 cable (23AWG) Imax ~0.7A, for two pairs (2x0.7)A [3](http://www.powerstream.com/Wire_Size.htm)
* additional loads
 * embedded board
 * SDR dongle
 * LNA
* Protection

Choices:
* ubiquiti-24-24w, 24V@1A (~14€)

**Comment by ppapadeas** [comment]
Selected one : ubiquiti-24-24w, 24V@1A (~14€)
