### ISSUE TITLE
Calibrate miniVNA-tiny

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-org#52]
We need to calibrate and publish calibration files for our new miniVNA-tiny.

**Comment by ppapadeas** [comment]
Uploaded the reflection calibration
https://github.com/satnogs/satnogs-org/commit/468b01be4646ac641df5b20f6e3bf94c60262333

**Comment by ppapadeas** [comment]
Need to upload tx cal

**Comment by zisi** [comment]
Uploaded the transmission calibration file
https://github.com/satnogs/satnogs-org/commit/dfef868ba4b9603d7fc2e89cff327de8df086692
