### ISSUE TITLE
HAM radio association research

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-org#57]

**Comment by ppapadeas** [comment]
http://www.yme.gr/?tid=263&aid=0
http://www.yme.gr/imagebank/categories/ctg745_9_1192093566.pdf

Άρθρο 7, παρ. 2 [pdf page 5]:
("...Άδεια ραδιοερασιτεχνικού σταθμού ασυρμάτου λαμ−
βάνουν:...")
"2. Τα μη κερδοσκοπικά σωματεία ή σύλλογοι που πλη−
ρούν τις παρακάτω προϋποθέσεις:
2.1. Έχουν συσταθεί και λειτουργούν νόμιμα.
2.2. Από το καταστατικό τους προκύπτει ότι αποσκο−
πούν στην υποστήριξη και ανάπτυξη της υπηρεσίας
ραδιοερασιτέχνη.
2.3. Υπάρχει απόφαση του σωματείου ή συλλόγου με
την οποία ορίζεται μέλος του, αδειούχος ραδιοερασιτέ−
χνης «κατηγορίας 1», ως ο υπεύθυνος λειτουργίας του
ραδιοερασιτεχνικού σταθμού (club station)."

**Comment by ppapadeas** [comment]
Ask legal

**Comment by comzeradd** [comment]
Legal gave green light
