### ISSUE TITLE
"On media" on main site

### ISSUE THREAD

**Issue by comzeradd** [satnogs/satnogs-org#75]
We should probably have a place on our website to add media references ([example](http://hackerpublicradio.org/eps.php?id=1702))

**Comment by ppapadeas** [comment]
Investigate WP plugin.

**Comment by comzeradd** [comment]
Plugin installed. We should know identify all the media/social quotes we feel we should mention.

**Comment by ppapadeas** [comment]
@elkos is the expert on this :) Any list we can use?

**Comment by elkos** [comment]
@ppapadeas Nope. but I started adding draft testimonials in plugins interface with quotes for us too pick

**Comment by ppapadeas** [comment]
Need to fix css.
