### ISSUE TITLE
Create LinkedIn page for LSF and for satNOGS project

### ISSUE THREAD

**Issue by papamat** [satnogs/satnogs-org#82]

**Comment by comzeradd** [comment]
@elkos  LinkedIn has "projects, which probably is more suitable for SatNOGS instead of page.

**Comment by jinxcat** [comment]
"project" for satnogs

And this for LSF:
https://smallbusiness.linkedin.com/small-business-marketing/building-your-brand

**Comment by ppapadeas** [comment]
Create LSF company page still needed.
