### ISSUE TITLE
Setup vm1.satnogs.org

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-org#95]
For migration of:
- satnogs.org
- librespacefoundation.org
- community.satnogs.org
- mail.satnogs.org

**Comment by comzeradd** [comment]
We should start phasing out the mailing list. No need to migrate mailman.

**Comment by comzeradd** [comment]
Things pending yet:

2 Wordpress sites: lsf, satnogs
1 Discoursse: satnogs

**Comment by comzeradd** [comment]
Discourse has been migrated. Pinging @axilleas in case he wants to complete the wordpress ansible role.

One more thing not listed here is the Owncloud, that ideally should be migrate to Nextcloud.

**Comment by axilleas** [comment]
Did you change anything in https://github.com/satnogs/satnogs-ansible?

**Comment by comzeradd** [comment]
Nope. At least nothing related to the Wordpress role. But I haven't tested it either.

**Comment by comzeradd** [comment]
DNS is still propagating, but all sites are moved to vm1
