### ISSUE TITLE
Create designs for Hamvension

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-org#96]
And send them to cshields.

Link
http://www.staples.com/sbd/content/copyandprint/deals/10marketingevent.html?PID=552179&CID=AFF%3A552179%3A552179%3A10428703&icid=HP%3ALPB%3A1%3A10DEALS%3A20150315&cm_mmc=CJ-_-552179-_-552179-_-10428703&SID=VlFtSURnb0tNckVBQUNJNGVnTUFBQUFr&CJPIXEL=CJPIXEL&AID=10428703&storeId=10001

**Comment by cshields** [comment]
:+1:
